export const ERROR_CODES = {
  ERR_UI_001: "Email hoặc số điện thoại không đúng định dạng",
  ERR_UI_002: "Mật khẩu tối thiểu 8 ký tự, gồm 1 chữ hoa và 1 số",
  ERR_UI_003: "Sai thông tin đăng nhập",
  ERR_UI_004: "Tài khoản bị khóa 30 phút",
  ERR_UI_005: "Mã OTP không hợp lệ hoặc đã hết hạn",
  ERR_UI_010: "Không tìm thấy xe phù hợp",
  ERR_UI_011: "Hết hàng giao ngay",
  ERR_UI_030: "Trùng slot lịch lái thử",
  ERR_UI_031: "Sai định dạng số điện thoại",
  ERR_UI_040: "Hết Quota xe",
  ERR_UI_041: "Cảnh báo timeout 3 phút",
  ERR_UI_042: "Nộp thiếu tiền cọc",
  ERR_UI_043: "Thanh toán thất bại",
  ERR_UI_050: "Ngân hàng từ chối cho vay",
  ERR_UI_051: "Đã đổi ngân hàng quá 3 lần",
  ERR_UI_052: "Số tiền vay vượt quá 80% giá xe",
  ERR_UI_060: "Thiếu trường dữ liệu bắt buộc",
  ERR_UI_061: "Xe cũ bị thủy kích, hủy cấn trừ",
  ERR_UI_070: "Thiếu chứng từ từ chối vay",
  ERR_UI_071: "Đơn hoàn cọc đã được xử lý",
  ERR_UI_080: "Số VIN không khả dụng",
  ERR_UI_081: "Vi phạm nguyên tắc SoD 4 Mắt",
  ERR_UI_090: "Chuyển trạng thái vi phạm State Machine",
  ERR_UI_091: "Lead đã bị re-assign",
  ERR_UI_100: "Chiết khấu vượt quá 10%",
  ERR_UI_101: "Không có quyền decrypt PII",
  ERR_RATE_LIMIT_EXCEEDED: "Vượt quá giới hạn thao tác",
} as const;
