export const ORDER_STATUS = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  DEPOSIT_PAID: "DEPOSIT_PAID",
  BANK_APPROVING: "BANK_APPROVING",
  BANK_APPROVED: "BANK_APPROVED",
  BANK_PARTIALLY_APPROVED: "BANK_PARTIALLY_APPROVED",
  BANK_REJECTED: "BANK_REJECTED",
  PROCESSING: "PROCESSING",
  READY_FOR_DELIVERY: "READY_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  COMPLETED: "COMPLETED",
  REFUND_REQUESTED: "REFUND_REQUESTED",
  REFUNDED: "REFUNDED",
  CANCELED: "CANCELED",
} as const;

export type OrderStatus = (typeof ORDER_STATUS)[keyof typeof ORDER_STATUS];

export const ORDER_STATUS_LABELS: Record<OrderStatus, string> = {
  PENDING_PAYMENT: "Chờ thanh toán",
  PAYMENT_FAILED: "Thanh toán thất bại",
  DEPOSIT_PAID: "Đã đặt cọc",
  BANK_APPROVING: "Đang thẩm định",
  BANK_APPROVED: "Ngân hàng duyệt",
  BANK_PARTIALLY_APPROVED: "Duyệt một phần",
  BANK_REJECTED: "Ngân hàng từ chối",
  PROCESSING: "Đang xử lý",
  READY_FOR_DELIVERY: "Sẵn sàng giao xe",
  DELIVERED: "Đã giao xe",
  COMPLETED: "Hoàn thành",
  REFUND_REQUESTED: "Yêu cầu hoàn cọc",
  REFUNDED: "Đã hoàn cọc",
  CANCELED: "Đã hủy",
};

export const VALID_TRANSITIONS: Record<OrderStatus, OrderStatus[]> = {
  PENDING_PAYMENT: ["DEPOSIT_PAID", "PAYMENT_FAILED", "CANCELED"],
  PAYMENT_FAILED: ["PENDING_PAYMENT", "CANCELED"],
  DEPOSIT_PAID: ["BANK_APPROVING", "PROCESSING", "REFUND_REQUESTED", "CANCELED"],
  BANK_APPROVING: ["BANK_APPROVED", "BANK_PARTIALLY_APPROVED", "BANK_REJECTED"],
  BANK_APPROVED: ["PROCESSING"],
  BANK_PARTIALLY_APPROVED: ["BANK_APPROVING", "PROCESSING", "REFUND_REQUESTED"],
  BANK_REJECTED: ["BANK_APPROVING", "REFUND_REQUESTED"],
  PROCESSING: ["READY_FOR_DELIVERY"],
  READY_FOR_DELIVERY: ["DELIVERED"],
  DELIVERED: ["COMPLETED"],
  COMPLETED: [],
  REFUND_REQUESTED: ["REFUNDED", "DEPOSIT_PAID"],
  REFUNDED: [],
  CANCELED: [],
};
